language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - "pip install flake8"
  - "pip install ."
script:
  - "python -m test.engine"
  - "flake8 rpncalculator"
  - "flake8 test"
