language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
script:
  - "python -m test.engine"
  - "python -m test.parser"
  - "flake8 rpncalculator"
  - "flake8 test"
